version: '3'
services:
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    deploy:
      mode: replicated
      replicas: 3

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
      - --config.file=/etc/prometheus/prometheus.yml

  custom-exporter:
    build: ./exporter
    container_name: custom-exporter
    ports:
      - 9000:9000
    depends_on: 
      - mysql
