global:
    scrape_interval: 15s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'custom-exporter'
      static_configs:
          - targets: ['custom-exporter:9000']